apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce 
  volumeName: mongodb-volume
  resources:
    requests:
      storage: 2Gi
status: {}