apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/argoproj/argocd-applicationset
  newName: quay.io/argoproj/argocd-applicationset
  newTag: latest

resources:
- secret.yaml
- mongodb-pvc.yaml
- mongodb-pv.yaml
- ../../base/deployment.yaml
- ../../base/service.yaml