apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-app-set
spec:
  generators:
    - git:
        repoURL: https://github.com/94peter/argo_infra.git
        revision: HEAD
        directories:
          - path: mongo/overlays/*
  template: # used to generate Argo CD Application resources
    metadata:
      name: 'infra-{{path.basename}}'
    spec:
      project: infra
      source:
        repoURL: https://github.com/94peter/argo_infra.git
        targetRevision: HEAD
        path: '{{path}}' # myapp/overlays/dev, myapp/overlays/prod
      destination:
        server: https://kubernetes.default.svc # https://dev.cluster.server, https://prod.cluster.server
        namespace: 'infra-{{path.basename}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true